mysql:
    host: localhost
    user: root
    passwd: sketch
    db: sketch
production-s3:
    host: 127.0.0.1
    key: minioadmin
    pass: minioadmin
    port: 9000
    bucket_name: image
legacy-s3:
    host: 127.0.0.1
    key: minioadmin
    pass: minioadmin
    port: 9000
    bucket_name: image