mysql:
    host: localhost
    user: root
    passwd: sketch
    db: sketch
s3_source:
    host: 127.0.0.1
    key: minioadmin
    pass: minioadmin
    port: 9000
s3_destination:
    host: 127.0.0.1
    key: minioadmin
    pass: minioadmin
    port: 9000